<?php

//use Drupal\Core\Serialization\Yaml;
use Drupal\webform\Controller\WebformResultsExportController;
use Drupal\webform\Entity\Webform;
//use Drupal\webform\Form\WebformResultsClearForm;
//use Drupal\webform\Form\WebformSubmissionsPurgeForm;
//use Drupal\webform\Utility\WebformYaml;
//use Psr\Log\LogLevel;

function webform_scheduled_export_cron() {

  //$webform = Webform::load($webform_id);
  $webform = Webform::load('contact_us');
  $source_entity = NULL;

  /** @var \Drupal\webform\WebformSubmissionExporterInterface $submission_exporter */
  $submission_exporter = \Drupal::service('webform_submission.exporter');
  $submission_exporter->setWebform($webform);
  $submission_exporter->setSourceEntity($source_entity);

/*
  // Get command options as export options.
  $export_options = drush_redispatch_get_options();
  // Convert dashes to underscores.
  foreach ($export_options as $key => $value) {
    unset($export_options[$key]);
    $export_options[str_replace('-', '_', $key)] = $value;
  }
 */
  //$export_options += $submission_exporter->getDefaultExportOptions();
	$export_options = $submission_exporter->getDefaultExportOptions();
	//file_put_contents('C:\Users\david\Clients\Sensis\Altamed\tmp\submission_export_options.txt', print_r($export_options, true));
  $submission_exporter->setExporter($export_options);

  WebformResultsExportController::batchSet($webform, $source_entity, $export_options);

  $file_path = ($submission_exporter->isArchive()) ? $submission_exporter->getArchiveFilePath() : $submission_exporter->getExportFilePath();

}
